apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.demo-app: semver:~1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: demo-app
        image: shashankbarsin/demo-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
