on:
  push:
    branches:
      - main
    paths:
      - manifests/*
  workflow_dispatch:
    branches:
      - main

jobs:      
  deploy-to-cluster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
      
    - uses: azure/k8s-set-context@cluster-connect
      with:
        cluster-type: 'arc'
        creds: '${{ secrets.AZURE_CREDS }}'
        token: '${{ secrets.SA_TOKEN }}'
        resource-group: 'shasbakstest'
        cluster-name: 'shasbakstest'   
        
    - run: |
        kubectl apply -f manifests/namespace.yaml
        kubectl apply -f manifests/deployment.yaml
        kubectl apply -f manifests/service.yaml
                          
